# телефонная книга куда и как подключаемся
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    webservers:
      hosts:
        localhost
    dbservers:
      hosts:
        localhost
    appservers:
      hosts:
        localhost
